env:
    QT_VERSION: '5.15.2'
    TCL_VERSION: '8.6'
    SQLITE_VERSION: '3470100'
    SQLITE_RELEASE_YEAR: '2024'
    PYTHON_VERSION: '3.9'
    ICU_VERSION: '72.1'
    PORTABLE_DIR: ${{ github.workspace }}/output/portable/SQLiteStudio
    INSTALLBUILDER_DIR: ../ib
    INSTALLBUILDER_URL: https://releases.bitrock.com/installbuilder/installbuilder-enterprise-24.3.0-osx-installer.dmg

name: MacOSX release build

on:
    workflow_dispatch:
        inputs:
          use_ccache:
            description: 'Use ccache (for workflow debugging only!)'
            required: false
            type: boolean
    schedule:
        - cron: '0 3 * * 1' # run at 3 AM UTC every Monday
    repository_dispatch:
        types: [mac_release]

jobs:
    build:
        runs-on: macos-13

        steps:
            - name: Debug
              shell: bash
              run: |
                brew search tcl-tk
                #find / -name tclsh
                #echo "----"
                #find / -name libtcl
                #echo "----"
                #find / -name tclConfig.sh
                # ls -l /usr/local/
                # ls -l /usr/local/include
                # ls -l /usr/local/opt/
                # ls -l /usr/local/opt/openssl/include/
                # ls -l /usr/local/opt/expat/include

