env:
    QT_VERSION: '6.8.0'
    QT_ARCH: 'win64_mingw'
    SQLITE_VERSION: '3470100'
    SQLITE_RELEASE_YEAR: '2024'
    PYTHON_VERSION: '3.13'
    ICU_VER: '75'
    ICU_URL: https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-icu-75.1-2-any.pkg.tar.zst
    MINGW_DIRNAME: mingw1310_64
    PORTABLE_DIR: output/portable/SQLiteStudio
    INSTALLBUILDER_DIR: ../ib
    MINGW_URL: https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw1310/qt.tools.win64_mingw1310/13.1.0-202407240918mingw1310.7z
    INSTALLBUILDER_URL: https://releases.installbuilder.com/installbuilder/installbuilder-enterprise-24.3.0-windows-x64-installer.exe

name: Windows 64-bit release build

on:
    workflow_dispatch:
        inputs:
          use_ccache:
            description: 'Use ccache (for workflow debugging only!)'
            required: false
            type: boolean
    schedule:
        - cron: '0 2 * * 1' # run at 2 AM UTC every Monday
    repository_dispatch:
        types: [win64_release]

jobs:
    build:
        runs-on: windows-2019

        steps:
            - name: fix path
              shell: bash
              run: |
                set -x
                echo $PATH
                export PATH=$(echo "$PATH" | tr ':' '\n' | grep -v "/mingw64/bin" | tr '\n' ':')
                export PATH=${PATH%:}
                echo $PATH
                echo $PATH > $GITHUB_PATH

            - name: debug
              shell: bash
              run: |
                echo "PATH: $PATH"
        